version: '3'
services:
  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - pgdb

  pgdb:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: kadaster_db
      POSTGRES_USER: kadaster_user
      POSTGRES_PASSWORD: kadaster_password
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null
